# # SERVER
# SERVER_PORT: 8080
# ACTIVE_PROFILE: prod

# # DATABASE
# ACTIVE_PROFILE: prod
# FRONTEND_PORT: 3000
# FRONTEND_HOST: 156.17.130.184
# POSTRESQL_HOST: db
# POSTRESQL_DB: zpi_db2
# POSTRESQL_USER: postgres
# POSTRESQL_PASSWORD: asdlkj000

# # SECURITY
GOOGLE_CLIENT_ID: 333365127566-llqb3rl4kcvvcnurr7cih7s126iu0e5v.apps.googleusercontent.com

# #FRONTEND
FRONTEND_URL: http://${FRONTEND_HOST}

# # MAIL
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: 260452@student.pwr.edu.pl
MAIL_PASSWORD: uuun dmyp qfbz mtgh

VERIFY_RES_LEADER_URL: ${FRONTEND_URL}/theses
