services:

  backend:
    build: 
      context: zpi-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      POSTRESQL_HOST: my_postgres
      POSTRESQL_DB: zpi_db2
      POSTRESQL_USER: postgres
      POSTRESQL_PASSWORD: asdlkj000
    depends_on:
      - db

  frontend:
    build: 
      context: zpi-frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: asdlkj000
